LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib" -static-libstdc++ -static-libgcc "C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/libopengl32.a" "C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/libglu32.a" "C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/libglut32.a" 
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include"
CFLAGS   = $(INCS) -lglu32 -lglut32 -lopengl32
OUTDIR	= out
BIN     = $(OUTDIR)/toh.exe

win32:
	gcc.exe src/*.c -o $(BIN) $(CFLAGS)